# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: OnCommit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies and tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 mypy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count
    - name: mypy
      run: |
        mypy --strict littlemail.py
    - name: send notification email
      run: |
        python littlemail.py -s '[littlemail] OnCommit OK!' -f 3003974@qq.com --to 3003974@qq.com xinlin.zhang@hotmail.com --smtp smtp.qq.com -p ${{QQMAIL_PASS4GITHUB}} --debug
